# Generated by Django 4.2.11 on 2024-10-04 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_platform_id', models.CharField(max_length=255, unique=True, verbose_name='social platform ID')),
                ('name', models.CharField(max_length=255)),
                ('page_token', models.CharField(max_length=255, unique=True, verbose_name='page token')),
            ],
            options={
                'verbose_name': 'станица Facebook',
                'verbose_name_plural': 'станицы Facebook',
            },
        ),
        migrations.CreateModel(
            name='InstagramPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_platform_id', models.CharField(max_length=255, unique=True, verbose_name='social platform ID')),
                ('page_token', models.CharField(max_length=255, unique=True, verbose_name='page token')),
                ('facebook_page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.facebookpages')),
            ],
            options={
                'verbose_name': 'Станица Instagram',
                'verbose_name_plural': 'Станицы Instagram',
            },
        ),
    ]
